name =input("enter your name: ")
mail = input("enter your email: ")
mobile = input("enter your mobile number: ")
bank_name = input("enter your bank name: ")
ifsc = input("enter your IFSC code: ")
balance = input("enter your available balance: ")
print("\n--- Bank information---")
print("Name                        :",name)
print("Email                       :",mail)
print("Mobile number      :",mobile)
print("Bank Name             :",bank_name)
print("IFSC code                :",ifsc)
print("Available Balance  :",balance)
