name = input("Enter your name: ")
age = input("Enter your age: ")
dob = input("Enter your dob: ")
qualification = input("Enter your qualification:")
hobby = input("Enter your hobby: ")
phno = input("enter your phno: ")
print("\n--- Your Biodata ---")
print("Name         :", name)
print("Age          :", age)
print("Dob          :", dob)
print("Qualification:", qualification)
print("Hobby        :", hobby)
print("Phno         :", phno)
