name=(input("enter your name: "))
fathers =(input("enter your father's name: "))
mothers =(input("enter your mother's name: "))
brother =(input("enter your brother's name: "))
print("\n--- Your family names ---")
print("Name   :",name)
print("Fathers name :",fathers)
print("Mothers name :",mothers)
print("Brothers name:",brother)
